[package]
name = "fenv"
version = "0.2.0"
edition = "2024"
authors = ["Seokmin Hong <ghdtjrald240@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SeokminHong/fenv"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
